---
title: "rmd_script_analyse"
output: html_document
date: "2024-04-23"
---
Premier bloc de code : importation des librairies.
```{r}
library(dplyr)
library(ggplot2)
library(tidytext)
library(tm)
library(knitr)
library(SemNetCleaner)
data("stop_words")
```
Deuxième bloc de code : définition des variables.
```{r}

#----------------------------- 
earthworms <- read.csv("~/Documents/GitHub/EarthwormsMetanalysis/ExtractionBiblio/metaanalyse_csv_final.csv")
abstracts<-c()
bing<-get_sentiments("bing")
#--------------------- 
names(earthworms)
n = nrow(earthworms)
```
Troisième bloc de code: ajout d'une colonne "aboutEarthworms".
```{r}
earthworms <- earthworms %>% mutate(aboutEarthworms = rep(TRUE,n))
```
Quatrième bloc de code: Construction de la liste des abstracts.
```{r}
 for (i in 1:n){
   abstract.i <-earthworms$Abstract[i]
   abstracts <- c(abstracts, abstract.i)
 }
```
Cinquième bloc de code : Construction d'un dataframe de tokens.
```{r}
 # Unnest tokens for the current abstract
unnested_tokens <- tibble(abstracts) %>%
unnest_tokens(word, abstracts)
# Append the unnested tokens to the list
unnested_tokens<-unnested_tokens%>%anti_join(stop_words)
unnested_tokens<-unnested_tokens %>% rowwise() %>% mutate(word = singularize(word))
```
Analyse du dataframe: 
```{r}
ordre=unnested_tokens %>%
     count(word, sort = TRUE) %>%
     filter(n > 100) %>%
     mutate(word = reorder(word, n,decreasing=TRUE))

 ordre$word = factor(ordre$word,levels=rev(levels(ordre$word)))
 ggplot(ordre,aes(n, word)) +
     geom_col() +
     labs(y = NULL)
```


